### ISSUE TITLE
const char* parameter

### ISSUE THREAD

**Issue by sunh3** [TheNumbat/cpp-course#2]
Hi

Reading through your c++ lessons and love it.

Regarding [this](https://thenumbat.github.io/cpp-course/cpp/10/10.html#params) const char* pointer parameter, you are saying the pointer can not be moved but the pointed-to data can be modified, but my code snippet shows the other way around.

the pointer value [can be changed to point to somewhere else](https://onlinegdb.com/H1w5CoRsV), but the pointed-to value cannot be changed, in VS compiler complains and says 'expression must be a modifiable lvalue'.

**Comment by TheNumbat** [comment]
Good catch - I'll update it shortly. (Edit: tomorrow)

**Comment by TheNumbat** [comment]
Updated
